version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      # Para desenvolvimento: mount do código para hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped